dataverse:
  host: "sapi-tcct-dataverse-v1-uat.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""

datalake:
  host: "sapi-tcct-datalake-v1-uat.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""
  
snowflake:
  host: "sapi-tcct-snowflake-v1-uat.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""
  
sqlserver:
  host: "sapi-tcct-sql-server-v1-uat.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""

cloudhub:
  env_id: "3881b1d4-dae0-4ba4-a199-c28c9d62147e"
  client_id: "0fd877431f3c4ffdb7af1ae2c6021006"
  # Por seguridad, se informa por variable de entorno
  client_secret: ""