tablas:
  "618":
    # Listado de tablas a procesar
    listado: [
          "Albaranes",
          "PP_CECO",
          "PP_Plantilla_PerioGastos_PEP",
          "PP_Plantilla_PerioIngreso_PEP",
          "PP_Plantilla_ProvGastos_PEP",
          "PP_Plantilla_ProvIngreso_PEP",
          "PP_PEP_Compra_Desagrupado",
          "rfs",
          "PP_Expediciones",
          "PP_PEP_Venta",
          "PP_PEP_Venta_Desagrupado"
      ]
      
    #Mapeos de tablas
    Albaranes:
      tablename: "Albaranes"
      origin: "sqlserver"
      Cantidad_del_pedido: "CANTIDAD_DEL_PEDIDO"
      Documento_compras: "DOCUMENTO_COMPRAS"
      Documento_de_ventas: "DOCUMENTO_DE_VENTAS"
      Elemento_PEP: "ELEMENTO_PEP"
      Fecha_documento: "FECHA_DOCUMENTO"
      Fecha_fin_pedido_venta: "FECHA_FIN_PEDIDO_VENTA"
      Fecha_inicio_pedido_venta: "FECHA_INICIO_PEDIDO_VENTA"
      Importe_pedido: "IMPORTE_PEDIDO"
      Moneda: "MONEDA"
      Moneda_documento: "MONEDA_DOCUMENTO"
      N_Pedido_Cliente: "N_PEDIDO_CLIENTE"
      PEP: "PEP"
      PEP_N3: "PEP_N3"
      Proveedor_Centro_suministrador: "PROVEEDOR_CENTRO_SUMINISTRADOR"
      Responsable_PEP_N2: "RESPONSABLE_PEP_N2"
      ROS_TSOL: "ROS_TSOL"
      SA: "SA"
      Texto_breve: "TEXTO_BREVE"
      Tipo_solicitud: "TIPO_SOLICITUD"
      Tramitador: "TRAMITADOR"
     
    PP_CECO:
      tablename: "PP_CECO"
      origin: "sqlserver"
      CantidadPedido: "CANTIDADPEDIDO"
      CecoCecoBoc: "CECOCECOBOC"
      ClaveReferencia1: "CLAVEREFERENCIA1"
      ClaveReferencia2: "CLAVEREFERENCIA2"
      ClaveReferencia3: "CLAVEREFERENCIA3"
      CuentaMayor: "CUENTAMAYOR"
      DocumentoCompras: "DOCUMENTOCOMPRAS"
      EntradaMercancias: "ENTRADAMERCANCIAS"
      EstadoExpedicion: "ESTADOEXPEDICION"
      FechaDocumento: "FECHADOCUMENTO"
      FechaFin: "FECHAFIN"
      FechaInicio: "FECHAINICIO"
      FechaPlan: "FECHAPLAN"
      ID: "ID"
      ImportePendExpedir: "IMPORTEPENDEXPEDIR"
      ImporteTotExpedido: "IMPORTETOTEXPEDIDO"
      ImporTotExpConfPendApro: "IMPORTOTEXPCONFPENDAPRO"
      ImporTotExpPendConfirmar: "IMPORTOTEXPPENDCONFIRMAR"
      ImportTotExpContabilizado: "IMPORTTOTEXPCONTABILIZADO"
      Moneda: "MONEDA"
      Parcial: "PARCIAL"
      PrecioNeto: "PRECIONETO"
      ProveedorCentroSuministrador: "PROVEEDORCENTROSUMINISTRADOR"
      SociedadGL: "SOCIEDADGL"
      TextoBreve: "TEXTOBREVE"
      TextoPosicion: "TEXTOPOSICION"
      TotalPeriodificaciones: "TOTALPERIODIFICACIONES"
      TotalProvisiones: "TOTALPROVISIONES"
      
    PP_Plantilla_PerioGastos_PEP:
      tablename: "PP_Plantilla_PerioGastos_PEP"
      origin: "sqlserver"
      _20ago: "_20AGO"
      _20dic: "_20DIC"
      _20nov: "_20NOV"
      _20oct: "_20OCT"
      _20sep: "_20SEP"
      _21abr: "_21ABR"
      _21ago: "_21AGO"
      _21dic: "_21DIC"
      _21ene: "_21ENE"
      _21feb: "_21FEB"
      _21jul: "_21JUL"
      _21jun: "_21JUN"
      _21mar: "_21MAR"
      _21may: "_21MAY"
      _21nov: "_21NOV"
      _21oct: "_21OCT"
      _21sep: "_21SEP"
      _22abr: "_22ABR"
      _22ago: "_22AGO"
      _22dic: "_22DIC"
      _22ene: "_22ENE"
      _22feb: "_22FEB"
      _22jul: "_22JUL"
      _22jun: "_22JUN"
      _22mar: "_22MAR"
      _22may: "_22MAY"
      _22nov: "_22NOV"
      _22oct: "_22OCT"
      _22sep: "_22SEP"
      _23abr: "_23ABR"
      _23ago: "_23AGO"
      _23dic: "_23DIC"
      _23ene: "_23ENE"
      _23feb: "_23FEB"
      _23jul: "_23JUL"
      _23jun: "_23JUN"
      _23mar: "_23MAR"
      _23may: "_23MAY"
      _23nov: "_23NOV"
      _23oct: "_23OCT"
      _23sep: "_23SEP"
      _24abr: "_24ABR"
      _24ago: "_24AGO"
      _24dic: "_24DIC"
      _24ene: "_24ENE"
      _24feb: "_24FEB"
      _24jul: "_24JUL"
      _24jun: "_24JUN"
      _24mar: "_24MAR"
      _24may: "_24MAY"
      _24nov: "_24NOV"
      _24oct: "_24OCT"
      _24sep: "_24SEP"
      _25abr: "_25ABR"
      _25ago: "_25AGO"
      _25dic: "_25DIC"
      _25ene: "_25ENE"
      _25feb: "_25FEB"
      _25jul: "_25JUL"
      _25jun: "_25JUN"
      _25mar: "_25MAR"
      _25may: "_25MAY"
      _25nov: "_25NOV"
      _25oct: "_25OCT"
      _25sep: "_25SEP"
      _26abr: "_26ABR"
      _26ago: "_26AGO"
      _26dic: "_26DIC"
      _26ene: "_26ENE"
      _26feb: "_26FEB"
      _26jul: "_26JUL"
      _26jun: "_26JUN"
      _26mar: "_26MAR"
      _26may: "_26MAY"
      _26nov: "_26NOV"
      _26oct: "_26OCT"
      _26sep: "_26SEP"
      _27abr: "_27ABR"
      _27ago: "_27AGO"
      _27dic: "_27DIC"
      _27ene: "_27ENE"
      _27feb: "_27FEB"
      _27jul: "_27JUL"
      _27jun: "_27JUN"
      _27mar: "_27MAR"
      _27may: "_27MAY"
      _27nov: "_27NOV"
      _27oct: "_27OCT"
      _27sep: "_27SEP"
      _28abr: "_28ABR"
      _28ago: "_28AGO"
      _28dic: "_28DIC"
      _28ene: "_28ENE"
      _28feb: "_28FEB"
      _28jul: "_28JUL"
      _28jun: "_28JUN"
      _28mar: "_28MAR"
      _28may: "_28MAY"
      _28nov: "_28NOV"
      _28oct: "_28OCT"
      _28sep: "_28SEP"
      ceco: "CECO"
      comentariosContables: "COMENTARIOSCONTABLES"
      comprobacion: "COMPROBACION"
      conversionMoneda: "CONVERSIONMONEDA"
      cuentaContable: "CUENTACONTABLE"
      descripcion: "DESCRIPCION"
      emRealizadaMD: "EMREALIZADAMD"
      emRealizadaML: "EMREALIZADAML"
      emTipo: "EMTIPO"
      entradaMercancia: "ENTRADAMERCANCIA"
      fechaFin: "FECHAFIN"
      fechaInicio: "FECHAINICIO"
      hitoConst: "HITOCONST"
      hitoConstML: "HITOCONSTML"
      hitoFinal: "HITOFINAL"
      hitoFinalML: "HITOFINALML"
      hitoInicial: "HITOINICIAL"
      hitoInicialML: "HITOINICIALML"
      hitos: "HITOS"
      ID: "ID"
      IDRegistro: "IDREGISTRO"
      importeMensual: "IMPORTEMENSUAL"
      importePeriodificado: "IMPORTEPERIODIFICADO"
      importeTechMD: "IMPORTETECHMD"
      importeTechML: "IMPORTETECHML"
      mesContable: "MESCONTABLE"
      moneda: "MONEDA"
      numProvClaveRef3: "NUMPROVCLAVEREF3"
      pedidoTSOL: "PEDIDOTSOL"
      pedTechClave: "PEDTECHCLAVE"
      pep: "PEP"
      periodificacion: "PERIODIFICACION"
      posicion: "POSICION"
      TIPO: "TIPO"
      totalGeneral: "TOTALGENERAL"

    PP_Plantilla_PerioIngreso_PEP:
      tablename: "PP_Plantilla_PerioIngreso_PEP"
      origin: "sqlserver"
      CECOResponsable: "CECORESPONSABLE"
      CentroDeBeneficio: "CENTRODEBENEFICIO"
      ClienteFacturacion: "CLIENTEFACTURACION"
      CuentaIngresos: "CUENTAINGRESOS"
      DenominacionElementoPEP: "DENOMINACIONELEMENTOPEP"
      DenominacionProyecto: "DENOMINACIONPROYECTO"
      DescrClienteFacturacion: "DESCRCLIENTEFACTURACION"
      DescrStatus: "DESCRSTATUS"
      DocumentoContable: "DOCUMENTOCONTABLE"
      DocumentoVentas: "DOCUMENTOVENTAS"
      ElementoPEP: "ELEMENTOPEP"
      FechaFacturaEmitida: "FECHAFACTURAEMITIDA"
      FechaReparto: "FECHAREPARTO"
      ID: "ID"
      IDRegistro: "IDREGISTRO"
      IDSubactividad: "IDSUBACTIVIDAD"
      ImporteFacturadoML: "IMPORTEFACTURADOML"
      ImporteHito: "IMPORTEHITO"
      MonedaDocumento: "MONEDADOCUMENTO"
      NPedidocliente: "NPEDIDOCLIENTE"
      Posicion: "POSICION"
      ReferenciaFactura: "REFERENCIAFACTURA"
      Responsable: "RESPONSABLE"
      SociedadGL: "SOCIEDADGL"
      Texto: "TEXTO"
      TextoPosicionPedido: "TEXTOPOSICIONPEDIDO"
      Tipificacion: "TIPIFICACION"
      TpCambio: "TPCAMBIO"

      

      
    PP_Plantilla_ProvGastos_PEP:
      tablename: "PP_Plantilla_ProvGastos_PEP"
      origin: "sqlserver"
      Asignacion: "ASIGNACION"
      BloqueoProyecto: "BLOQUEOPROYECTO"
      CentroCoste: "CENTROCOSTE"
      ClaveReferencia1: "CLAVEREFERENCIA1"
      ClaveReferencia2: "CLAVEREFERENCIA2"
      ClaveReferencia3: "CLAVEREFERENCIA3"
      ControlPresupuestario: "CONTROLPRESUPUESTARIO"
      CuentaMayor: "CUENTAMAYOR"
      CuentaMayorAsociada: "CUENTAMAYORASOCIADA"
      DH: "DH"
      ElementoPEP: "ELEMENTOPEP"
      FechaContable: "FECHACONTABLE"
      FechaDocumento: "FECHADOCUMENTO"
      ID: "ID"
      IDClienteDeudor: "IDCLIENTEDEUDOR"
      IDProveedorAcreedor: "IDPROVEEDORACREEDOR"
      IDRegistro: "IDREGISTRO"
      IDSociedadGL: "IDSOCIEDADGL"
      ImporteMD: "IMPORTEMD"
      ImporteML: "IMPORTEML"
      Moneda: "MONEDA"
      NombreAcreedorDeudor: "NOMBREACREEDORDEUDOR"
      OrdenInversion: "ORDENINVERSION"
      Referencia: "REFERENCIA"
      SecuenciaAsiento: "SECUENCIAASIENTO"
      TextoCabecera: "TEXTOCABECERA"
      TextoPosicion: "TEXTOPOSICION"
      TIPO: "TIPO"
      
    PP_Plantilla_ProvIngreso_PEP:
      tablename: "PP_Plantilla_ProvIngreso_PEP"
      origin: "sqlserver"
      Asignacion: "ASIGNACION"
      BloqueoProyecto: "BLOQUEOPROYECTO"
      CentroCoste: "CENTROCOSTE"
      Clave1: "CLAVE1"
      Clave2: "CLAVE2"
      Clave3: "CLAVE3"
      ControlPesupuestario: "CONTROLPESUPUESTARIO"
      CuentaMayor: "CUENTAMAYOR"
      CuentaMayorAsociada: "CUENTAMAYORASOCIADA"
      D/H: "D/H"
      ElementoPEP: "ELEMENTOPEP"
      FechaContable: "FECHACONTABLE"
      FechaDocumento: "FECHADOCUMENTO"
      ID: "ID"
      # Falta en SQLServer tabla IDACREDORDEUDOR (tabla Snowflake)
      IDCLiente: "IDCLIENTE"
      IDProveedorAcreedor: #***
      IDRegistro: "IDREGISTRO"
      IDSociedad: "IDSOCIEDAD"
      ImporteMD: "IMPORTEMD"
      ImporteML: "IMPORTEML"
      Moneda: "MONEDA"
      NombreAcreedorDeudor: "NOMBREACREDORDEUDOR"
      NPedido: "NPEDIDO"
      OrdenInversion: "ORDENINVERSION"
      Referencia: "REFERENCIA"
      SecuenciaAsiento: "SECUENCIAASIENTO"
      TextoCabecera: "TEXTOCABECERA"
      TextoPosicion: "TEXTOPOSICION"

            
    PP_PEP_Compra_Desagrupado:
      tablename: "PP_PEP_Compra_Desagrupado"
      origin: "sqlserver"
      CantidadPedido: "CANTIDADPEDIDO"
      CecoResponsable: "CECORESPONSABLE"
      ClaveReferencia1: "CLAVEREFERENCIA1"
      ClaveReferencia2: "CLAVEREFERENCIA2"
      ClaveReferencia3: "CLAVEREFERENCIA3"
      ClienteFuncional: "CLIENTEFUNCIONAL"
      CuentaMayor: "CUENTAMAYOR"
      CuentaMayorAsociada: "CUENTAMAYORASOCIADA"
      DocCompras: "DOCCOMPRAS"
      DocumentoVentas: "DOCUMENTOVENTAS"
      EntradaMercancias: "ENTRADAMERCANCIAS"
      EstadoExpedicion: "ESTADOEXPEDICION"
      EstadoPedidoVenta: "ESTADOPEDIDOVENTA"
      Fase: "FASE"
      FecDocumento: "FECDOCUMENTO"
      FecFin: "FECFIN"
      FechaHito: "FECHAHITO"
      FechaHitoDATETIME: "FECHAHITODATETIME"
      FechFinPedidoVenta: "FECHFINPEDIDOVENTA"
      FechFinPEPN2: "FECHFINPEPN2"
      FechInicio: "FECHINICIO"
      FechInicioPedidoVenta: "FECHINICIOPEDIDOVENTA"
      FechInicioPEPN2: "FECHINICIOPEPN2"
      FecPlan: "FECPLAN"
      ID: "ID"
      IDProveedor: "IDPROVEEDOR"
      IDSociedadGL: "IDSOCIEDADGL"
      ImporteMD: "IMPORTEMD"
      ImporteML: "IMPORTEML"
      ImportePedido: "IMPORTEPEDIDO"
      ImpPendExpedir: "IMPPENDEXPEDIR"
      ImpTotExpConfPendArpobar: "IMPTOTEXPCONFPENDARPOBAR"
      ImpTotExpContabilizado: "IMPTOTEXPCONTABILIZADO"
      ImpTotExpedido: "IMPTOTEXPEDIDO"
      ImpTotExpPendConfirmar: "IMPTOTEXPPENDCONFIRMAR"
      LeftNPedidoCli: "LeftNPedidoCli "
      MonedaDocumento: "MONEDADOCUMENTO"
      NombreAcreedor: "NOMBREACREEDOR"
      NPedidoCliente: "NPEDIDOCLIENTE"
      Parcial: "PARCIAL"
      PEP: "PEP"
      PEPN2: "PEPN2"
      PEPN3: "PEPN3"
      Posicion: "POSICION"
      PrecioNeto: "PRECIONETO"
      ProveedorCentroSum: "PROVEEDORCENTROSUM"
      PtoCompras: "PTOCOMPRAS"
      ResponsablePEPN2: "RESPONSABLEPEPN2"
      RFSPlan: "RFSPLAN"
      SA: "SA"
      SociedadGL: "SOCIEDADGL"
      TextoBreve: "TEXTOBREVE"
      TextoPosicion: "TEXTOPOSICION"
      TipoSolicitud: "TIPOSOLICITUD"
      TotalPeriodificaciones: "TOTALPERIODIFICACIONES"
      TotalProvisiones: "TOTALPROVISIONES"
      
    rfs:
      tablename: "rfs"
      origin: "sqlserver"
      AP: "AP"
      ClienteContable: "CLIENTECONTABLE"
      ClienteFacturacion: "CLIENTEFACTURACION"
      CostesTotPepn2: "COSTESTOTPEPN2"
      DefinicionProyecto: "DEFINICIONPROYECTO"
      Descripcion: "DESCRIPCION"
      DocumentoVentas: "DOCUMENTOVENTAS"
      EstadoExpedicion: "ESTADOEXPEDICION"
      EstadoPdv: "ESTADOPDV"
      Fase: "FASE"
      FechaCreacionSA: "FECHACREACIONSA"
      FechaEntreAlbaran: "FECHAENTREALBARAN"
      FechaFinPedidoVenta: "FECHAFINPEDIDOVENTA"
      FechaIniPedidoVenta: "FECHAINIPEDIDOVENTA"
      FechaPrevRFSTsol: "FECHAPREVRFSTSOL"
      FechaRFS: "FECHARFS"
      id: "ID"
      IdFase: "IDFASE"
      ImportePedido: "IMPORTEPEDIDO"
      Jdp: "JDP"
      MonedaDocumento: "MONEDADOCUMENTO"
      NPedidoCliente: "NPEDIDOCLIENTE"
      PedCompraAsociado: "PEDCOMPRAASOCIADO"
      PedidosRelacionados: "PEDIDOSRELACIONADOS"
      Pepn2: "PEPN2"
      RfsPlanTCCT: "RFSPLANTCCT"
      RfsRealTCCT: "RFSREALTCCT"
      SA: "SA"
      ServicioComercial: "SERVICIOCOMERCIAL"
      Tipologia: "TIPOLOGIA"
      Tipopedido: "TIPOPEDIDO"
      
    PP_Expediciones:
      tablename: "PP_Expediciones"
      origin: "sqlserver"
      CantidadPedido: "CANTIDADPEDIDO"
      CecoResponsable: "CECORESPONSABLE"
      DocumentoCompras: "DOCUMENTOCOMPRAS"
      EstadoExpedicion: "ESTADOEXPEDICION"
      Fase: "FASE"
      FechaDocumento: "FECHADOCUMENTO"
      FechaFin: "FECHAFIN"
      FechaFinPEPN2: "FECHAFINPEPN2"
      FechaInicio: "FECHAINICIO"
      FechaInicioPEPN2: "FECHAINICIOPEPN2"
      FechaPlan: "FECHAPLAN"
      FechaRFSPlan: "FECHARFSPLAN"
      FechaRFSReal: "FECHARFSREAL"
      ImpPendExpedir: "IMPPENDEXPEDIR"
      ImpTotConfPendApro: "IMPTOTCONFPENDAPRO"
      ImpTotExpedCont: "IMPTOTEXPEDCONT"
      ImpTotExpedido: "IMPTOTEXPEDIDO"
      ImpTotExpPendConf: "IMPTOTEXPPENDCONF"
      Origen: "ORIGEN"
      Parcial: "PARCIAL"
      PEP: "PEP"
      PEPN2: "PEPN2"
      PEPN3: "PEPN3"
      ProveedorCentroSuministrador: "PROVEEDORCENTROSUMINISTRADOR"
      ResponsablePEPN2: "RESPONSABLEPEPN2"
      SA: "SA"
      SociedadGL: "SOCIEDADGL"
      TextoBreve: "TEXTOBREVE"
      TotalPeriodificaciones: "TOTALPERIODIFICACIONES"
      TotalProvisiones: "TOTALPROVISIONES"
      
    PP_PEP_Venta:
      tablename: "PP_PEP_Venta"
      origin: "sqlserver"
      CECOResponsable: "CECORESPONSABLE"
      ClaveReferencia1: "CLAVEREFERENCIA1"
      ClaveReferencia2: "CLAVEREFERENCIA2"
      ClaveReferencia3: "CLAVEREFERENCIA3"
      ClienteContable: "CLIENTECONTABLE"
      ClienteFuncional: "CLIENTEFUNCIONAL"
      CuentaMayor: "CUENTAMAYOR"
      CuentaMayorAsociada: "CUENTAMAYORASOCIADA"
      DocVentas: "DOCVENTAS"
      EstadoPedidoVenta: "ESTADOPEDIDOVENTA"
      Fase: "FASE"
      FechaHito: "FECHAHITO"
      FechFinPedVenta: "FECHFINPEDVENTA"
      FechFinPEPN2: "FECHFINPEPN2"
      FechInicioPedVenta: "FECHINICIOPEDVENTA"
      FecInicioPEPN2: "FECINICIOPEPN2"
      IDCliente: "IDCLIENTE"
      IDClienteFacturacion: "IDCLIENTEFACTURACION"
      IDSociedadGL: "IDSOCIEDADGL"
      ImporteFacturadoTotal: "IMPORTEFACTURADOTOTAL"
      ImportePedido: "IMPORTEPEDIDO"
      ImportePendTotal: "IMPORTEPENDTOTAL"
      LeftNPedidoCli: "LEFTNPEDIDOCLI"
      MonedaDocumento: "MONEDADOCUMENTO"
      N47Asociado: "N47ASOCIADO"
      N49Asociado: "N49ASOCIADO"
      NombreAcreedor: "NOMBREACREEDOR"
      NPedidoCliente: "NPEDIDOCLIENTE"
      PEP: "PEP"
      PEPN2: "PEPN2"
      PEPN2Asociado: "PEPN2ASOCIADO"
      PtoCompras: "PTOCOMPRAS"
      Responsable: "RESPONSABLE"
      Responsable2: "RESPONSABLE2"
      RFSPlan: "RFSPLAN"
      RFSReal: "RFSREAL"
      SA: "SA"
      SociedadGL: "SOCIEDADGL"
      TextoPosicion: "TEXTOPOSICION"
      TipoSolicitud: "TIPOSOLICITUD"
      TotalPeriodificaciones: "TOTALPERIODIFICACIONES"
      TotalProvisiones: "TOTALPROVISIONES"
      
    PP_PEP_Venta_Desagrupado:
      tablename: "PP_PEP_Venta_Desagrupado"
      origin: "sqlserver"
      CECOResponsable: "CECORESPONSABLE"
      CECOResponsable2: "CECORESPONSABLE2"
      CentroBeneficio: "CENTROBENEFICIO"
      ClaveReferencia1: "CLAVEREFERENCIA1"
      ClaveReferencia2: "CLAVEREFERENCIA2"
      ClaveReferencia3: "CLAVEREFERENCIA3"
      ClienteContable: "CLIENTECONTABLE"
      ClienteFacturacion: "CLIENTEFACTURACION"
      ClienteFuncional: "CLIENTEFUNCIONAL"
      CuentaIngresos: "CUENTAINGRESOS"
      CuentaMayor: "CUENTAMAYOR"
      CuentaMayorAsociada: "CUENTAMAYORASOCIADA"
      DenominacionElemento: "DENOMINACIONELEMENTO"
      DenominacionProyecto: "DENOMINACIONPROYECTO"
      DescripStatus: "DESCRIPSTATUS"
      DocContable: "DOCCONTABLE"
      DocVentas: "DOCVENTAS"
      EstadoPedidoVenta: "ESTADOPEDIDOVENTA"
      Fase: "FASE"
      FechaFacturaEmitida: "FECHAFACTURAEMITIDA"
      FechaHito: "FECHAHITO"
      FechaHitoDATETIME: "FECHAHITODATETIME"
      FechFinPedVenta: "FECHFINPEDVENTA"
      FechFinPEPN2: "FECHFINPEPN2"
      FechInicioPedVenta: "FECHINICIOPEDVENTA"
      FecInicioPEPN2: "FECINICIOPEPN2"
      IDCliente: "IDCLIENTE"
      IDClienteFacturacion: "IDCLIENTEFACTURACION"
      IDSociedadGL: "IDSOCIEDADGL"
      IDSubactividad: "IDSUBACTIVIDAD"
      ImporteFacturadoML: "IMPORTEFACTURADOML"
      ImporteFacturadoTotal: "IMPORTEFACTURADOTOTAL"
      ImporteHitoMD: "IMPORTEHITOMD"
      ImportePedido: "IMPORTEPEDIDO"
      ImportePendTotal: "IMPORTEPENDTOTAL"
      LeftNPedidoCli: "LEFTNPEDIDOCLI"
      MonedaDocumento: "MONEDADOCUMENTO"
      N47Asociado: "N47ASOCIADO"
      N49Asociado: "N49ASOCIADO"
      NombreAcreedor: "NOMBREACREEDOR"
      NPedidoCliente: "NPEDIDOCLIENTE"
      PEP: "PEP"
      PEPN2: "PEPN2"
      PEPN2Asociado: "PEPN2ASOCIADO"
      PtoCompras: "PTOCOMPRAS"
      ReferenciaFactura: "REFERENCIAFACTURA"
      Responsable: "RESPONSABLE"
      Responsable2: "RESPONSABLE2"
      Responsable3: "RESPONSABLE3"
      RFSPlan: "RFSPLAN"
      RFSReal: "RFSREAL"
      SA: "SA"
      SociedadGL: "SOCIEDADGL"
      SociedadGL2: "SOCIEDADGL2"
      Texto: "TEXTO"
      TextoPosicion: "TEXTOPOSICION"
      TextoPosicionPed: "TEXTOPOSICIONPED"
      Tipificacion: "TIPIFICACION"
      TipoSolicitud: "TIPOSOLICITUD"
      TotalPeriodificaciones: "TOTALPERIODIFICACIONES"
      TotalProvisiones: "TOTALPROVISIONES"
      TpCambio: "TPCAMBIO"        
                        