dataverse:
  host: "sapi-tcct-dataverse-v1-dev.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""

datalake:
  host: "sapi-tcct-datalake-v1-dev.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""
  
snowflake:
  host: "sapi-tcct-snowflake-v1-dev.ir-e1.cloudhub.io"
  port: 
    insecure: "80"
    secure: "443"
  client_id: "c06620083a3b4c06bea14addb666b8b3"
  client_secret: ""

cloudhub:
  env_id: "026101c2-522a-4ebc-8ca8-8ae3bc565426"
  client_id: "79314592f7cb4944bb059af6dda16e29"
  # Por seguridad, se informa por variable de entorno
  client_secret: ""